# Generated by Django 5.1.2 on 2024-11-02 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_additionals'),
        ('products', '0004_remove_additional_maximum_remove_additional_minimum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='additionals',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='additionals',
            field=models.ManyToManyField(blank=True, to='products.additional'),
        ),
    ]
