# Generated by Django 5.1.2 on 2024-11-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_value',
            field=models.FloatField(default=0),
        ),
    ]
