# Generated by Django 5.1.2 on 2024-10-23 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('addition', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('maximum', models.IntegerField()),
                ('minimum', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('options', models.ManyToManyField(to='products.option')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('ingredients', models.CharField(max_length=2000)),
                ('active', models.BooleanField(default=True)),
                ('additionals', models.ManyToManyField(blank=True, to='products.additional')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
